/* ==========================================================================
   Gentleman Sailing — čo zažijete na regate?
   Nav scroll + mobile menu + SK/EN toggle (structural labels)
   ========================================================================== */
(function () {
  'use strict';

  var DICT = {
    nav_home: { sk: 'Domov', en: 'Home' },
    ev_info: { sk: 'Ako sa pripraviť na regatu', en: 'How to prepare' },
    ev_events: { sk: 'Eventy & teambuildingy', en: 'Events & teambuilding' },
    ev_partners: { sk: 'Partneri', en: 'Partners' },
    ev_signup: { sk: 'Prihláška', en: 'Sign up' },

    z_eyebrow: { sk: 'Čo zažijete na regate', en: 'What you’ll experience' },

    z_h1: { sk: "Regata, v ktorej nejde len o víťazstvo", en: "A regatta that is about more than winning" },
    z_lead: { sk: "Gentleman Sailing spája šport, dobrodružstvo, more, priateľstvo a noblesu. Na prvý pohľad je to súťaž plachetníc — v skutočnosti je to oveľa viac.", en: "Gentleman Sailing brings together sport, adventure, the sea, friendship and nobility. At first glance it is a sailing competition — in reality it is much more." },
    z_s1p1: { sk: "Gentleman Sailing regata je výnimočné jachtársko-spoločenské podujatie, ktoré spája šport, dobrodružstvo, more, priateľstvo a noblesu. Na prvý pohľad je to súťaž plachetníc. V skutočnosti je to však oveľa viac. Je to spôsob plavby, ktorý stojí na hodnotách fair play, rešpektu, férovosti, dôvery a spoločného zážitku.", en: "The Gentleman Sailing regatta is an exceptional sailing and social event that brings together sport, adventure, the sea, friendship and nobility. At first glance it is a sailing competition. In reality it is much more. It is a way of sailing built on the values of fair play, respect, fairness, trust and shared experience." },
    z_s1p2: { sk: "Gentleman Sailing nie je regata, v ktorej ide iba o to, kto ako prvý prepláva cieľovou čiarou. Je to regata, v ktorej je rovnako dôležité, ako sa k cieľu dostanete. S rešpektom k pravidlám. S úctou k súperom. S ohľaduplnosťou k posádke. S pokorou voči moru. A s vedomím, že skutočné víťazstvo sa nemeria iba časom, ale aj tým, akú atmosféru za sebou zanecháte.", en: "Gentleman Sailing is not a regatta that is only about who crosses the finish line first. It is a regatta where how you get there matters just as much. With respect for the rules. With respect for your rivals. With consideration for your crew. With humility towards the sea. And with the knowledge that true victory is measured not only in time, but also in the atmosphere you leave behind." },
    z_s1p3: { sk: "Gentleman Sailing je postavený na myšlienke, že súťažiť sa dá naplno, odvážne a s vášňou, no zároveň čestne, férovo a s noblesou. Práve táto kombinácia robí z regaty zážitok, ktorý si posádky pamätajú ešte dlho po návrate na pevninu.", en: "Gentleman Sailing is built on the idea that you can compete flat out, boldly and with passion, yet at the same time honestly, fairly and with nobility. It is this combination that makes the regatta an experience crews remember long after returning to shore." },
    z_mw_eb: { sk: "Pre mužov aj ženy", en: "For men and women" },
    z_mw_t: { sk: "Plavba pre mužov aj ženy", en: "Sailing for men and women" },
    z_mw_p1: { sk: "Hoci názov Gentleman Sailing prirodzene odkazuje na pojem gentleman, táto regata nie je určená iba pre mužov. Naopak. Gentleman Sailing je otvorený mužom aj ženám, skúseným jachtárom aj tým, ktorí si atmosféru regaty chcú zažiť po prvý raz.", en: "Although the name Gentleman Sailing naturally refers to the notion of a gentleman, this regatta is not meant for men only. Quite the opposite. Gentleman Sailing is open to men and women, to experienced sailors and to those who want to experience the atmosphere of a regatta for the first time." },
    z_mw_p2: { sk: "V tomto kontexte gentleman neznamená pohlavie. Znamená postoj. Znamená spôsob správania. Znamená úroveň, s akou človek vstupuje do súťaže, do tímu, do komunikácie aj do spoločného priestoru na palube.", en: "In this context, gentleman does not mean gender. It means attitude. It means a way of behaving. It means the standard with which a person enters the competition, the team, the communication and the shared space on board." },
    z_mw_p3: { sk: "Gentlemanská plavba je o tom, že každý člen posádky má svoje miesto. Každý je dôležitý. Každý môže prispieť. Niekto skúsenosťami, niekto odvahou, niekto pokojom, niekto energiou, niekto schopnosťou podržať tím v správnej chvíli.", en: "Gentleman sailing means every crew member has their place. Everyone matters. Everyone can contribute. Some with experience, some with courage, some with calm, some with energy, some with the ability to hold the team together at the right moment." },
    z_mw_p4: { sk: "Na palube nezáleží na tom, či ste muž alebo žena. Záleží na tom, či viete spolupracovať, počúvať, rešpektovať ostatných a byť súčasťou jednej posádky. More veľmi rýchlo ukáže, že dobrý tím nestojí na sile jednotlivca, ale na súhre všetkých.", en: "On board it does not matter whether you are a man or a woman. What matters is whether you can cooperate, listen, respect others and be part of one crew. The sea very quickly shows that a good team is built not on the strength of an individual, but on everyone working in harmony." },
    z_gp_eb: { sk: "Gentlemanská plavba", en: "Gentleman sailing" },
    z_gp_t: { sk: "Čo znamená gentlemanská plavba?", en: "What does gentleman sailing mean?" },
    z_gp_p1: { sk: "Gentlemanská plavba je spôsob plavby, ktorý spája športového ducha s ľudskou úrovňou. Je to prístup, pri ktorom sa rešpektuje súper, posádka, pravidlá, organizátor, loď aj samotné more.", en: "Gentleman sailing is a way of sailing that combines sporting spirit with human decency. It is an approach that respects the rival, the crew, the rules, the organiser, the boat and the sea itself." },
    z_gp_p2: { sk: "Nie je to plavba bez ambície. Práve naopak. Gentleman Sailing je regata, a teda prirodzene prináša napätie, taktiku, súťaživosť a túžbu vyhrať. Rozdiel je v tom, že víťazstvo nemá byť dosiahnuté za každú cenu.", en: "It is not sailing without ambition. Quite the opposite. Gentleman Sailing is a regatta, and so it naturally brings tension, tactics, competitiveness and the desire to win. The difference is that victory is not to be achieved at any cost." },
    z_gp_p3: { sk: "Gentlemanská plavba znamená, že posádka súťaží čestne. Nespolieha sa na nefér výhody, zbytočné konflikty ani pretláčanie ega. Hľadá najlepšiu trasu, pracuje s vetrom, sleduje konkurenciu, robí rozhodnutia v správny čas a využíva schopnosti celého tímu. No zároveň rešpektuje hranice, pravidlá a ducha regaty.", en: "Gentleman sailing means the crew competes honestly. It does not rely on unfair advantages, needless conflicts or ego contests. It looks for the best route, works with the wind, watches the competition, makes decisions at the right time and uses the abilities of the whole team. At the same time it respects the limits, the rules and the spirit of the regatta." },
    z_gp_p4: { sk: "Je to plavba, pri ktorej má význam nielen výkon, ale aj charakter.", en: "It is sailing where not only performance matters, but character too." },
    z_fp_t: { sk: "Fair play ako základ Gentleman Sailing", en: "Fair play as the foundation of Gentleman Sailing" },
    z_fp_p1: { sk: "Fair play je jednou z najdôležitejších hodnôt Gentleman Sailing regaty. Bez férovosti by regata stratila svoj zmysel. Jachting je šport, v ktorom sa súťaží v neustále sa meniacich podmienkach. Vietor, vlny, rozhodnutia posádky, taktika, skúsenosti aj schopnosť reagovať na situáciu vytvárajú prostredie, kde sa ukáže nielen technická zdatnosť, ale aj charakter.", en: "Fair play is one of the most important values of the Gentleman Sailing regatta. Without fairness, the regatta would lose its meaning. Yachting is a sport contested in constantly changing conditions. Wind, waves, crew decisions, tactics, experience and the ability to respond to a situation create an environment that reveals not only technical skill, but character." },
    z_fp_p2: { sk: "Fair play znamená rešpektovať pravidlá, aj keď sa nikto nepozerá. Znamená priznať si chybu. Znamená nesnažiť sa získať výhodu spôsobom, ktorý by bol v rozpore s duchom regaty. Znamená vedieť prijať výsledok, pogratulovať súperovi a pokračovať ďalej s úsmevom.", en: "Fair play means respecting the rules even when nobody is watching. It means admitting a mistake. It means not seeking an advantage in a way that goes against the spirit of the regatta. It means being able to accept the result, congratulate your rival and carry on with a smile." },
    z_fp_p3: { sk: "Na mori sa férovosť nedá iba predstierať. Posádky sa stretávajú na vode, v prístavoch, pri spoločných večeroch aj počas vyhodnotenia. Atmosféra celého podujatia stojí na tom, že medzi účastníkmi vzniká dôvera. Súperenie je skutočné, ale nie nepriateľské. Ambícia je prirodzená, ale nemá prekročiť hranicu rešpektu.", en: "At sea, fairness cannot be faked. Crews meet on the water, in the harbours, at shared dinners and at the prize-giving. The atmosphere of the whole event rests on the trust that grows between participants. The rivalry is real, but not hostile. Ambition is natural, but it must not cross the line of respect." },
    z_fp_p4: { sk: "Gentleman Sailing preto nie je len o pravidlách napísaných v propozíciách. Je aj o nepísaných pravidlách správania, ktoré robia z regaty kultivované podujatie s vlastným charakterom.", en: "Gentleman Sailing is therefore not only about the rules written in the notice of race. It is also about the unwritten rules of conduct that make the regatta a cultivated event with a character of its own." },
    z_su_eb: { sk: "Súťaživosť", en: "Competitiveness" },
    z_su_t: { sk: "Súťaživosť áno, rivalita nie", en: "Competitiveness yes, rivalry no" },
    z_su_p1: { sk: "Gentleman Sailing prináša súťaživosť, ktorá k regate prirodzene patrí. Posádky chcú byť rýchle, chcú zvládnuť manévre čo najlepšie, chcú správne čítať vietor a chcú prísť do cieľa s dobrým výsledkom. Práve táto energia dáva regate adrenalín a napätie.", en: "Gentleman Sailing brings the competitiveness that naturally belongs to a regatta. Crews want to be fast, to handle manoeuvres as well as possible, to read the wind correctly and to finish with a good result. It is this energy that gives the regatta its adrenaline and tension." },
    z_su_p2: { sk: "Rozdiel je v tom, že súťaživosť na Gentleman Sailing má priateľskú podobu. Posádky proti sebe nestoja ako nepriatelia. Sú súčasťou jedného podujatia, jednej komunity a jedného spoločného zážitku. Dnes sa predbehnú na vode, večer si spolu sadnú v prístave. Dnes bojujú o sekundy, zajtra si pomôžu s lanom, radou alebo dobrou náladou.", en: "The difference is that competitiveness at Gentleman Sailing takes a friendly form. Crews do not face each other as enemies. They are part of one event, one community and one shared experience. Today they overtake each other on the water; in the evening they sit down together in the harbour. Today they fight for seconds; tomorrow they help each other with a rope, advice or good cheer." },
    z_su_p3: { sk: "Takáto forma súťaže je pre Gentleman Sailing typická. Neuberá nič z napätia regaty, no dodáva jej ľudskosť. Víťazstvo chutí lepšie, keď prichádza v atmosfére rešpektu. A aj prehra sa prijíma ľahšie, keď je súčasťou férovej hry.", en: "This form of competition is typical of Gentleman Sailing. It takes nothing away from the tension of the regatta, but gives it humanity. Victory tastes better when it comes in an atmosphere of respect. And even defeat is easier to accept when it is part of a fair game." },
    z_no_eb: { sk: "Noblesa", en: "Nobility" },
    z_no_t: { sk: "Noblesa na vode aj na pevnine", en: "Nobility on the water and ashore" },
    z_no_p1: { sk: "Noblesa je slovo, ktoré ku Gentleman Sailing prirodzene patrí. Neznamená okázalosť ani formálnosť. Znamená úroveň. V správaní, v komunikácii, v súťaži aj v spoločných chvíľach mimo vody.", en: "Nobility is a word that naturally belongs to Gentleman Sailing. It does not mean ostentation or formality. It means standard. In behaviour, in communication, in competition and in the shared moments off the water." },
    z_no_p2: { sk: "Noblesa na vode znamená rešpektovať posádku, kapitána, ostatné lode aj pravidlá bezpečnosti. Znamená nepodceňovať more, nepodceňovať vietor a nepodceňovať zodpovednosť, ktorú má každý člen posádky. Znamená správať sa tak, aby sa ostatní na palube cítili bezpečne, prijato a súčasťou tímu.", en: "Nobility on the water means respecting the crew, the skipper, the other boats and the safety rules. It means not underestimating the sea, not underestimating the wind and not underestimating the responsibility each crew member carries. It means behaving so that everyone on board feels safe, welcome and part of the team." },
    z_no_p3: { sk: "Noblesa na pevnine znamená vedieť sa tešiť z výsledku bez povýšenosti. Vedieť prijať neúspech bez výhovoriek. Vedieť oceniť organizátorov, súperov, posádku aj ľudí, ktorí sa o podujatie starajú. Znamená priniesť so sebou dobrú atmosféru a prispieť k tomu, aby regata bola zážitkom pre všetkých.", en: "Nobility ashore means being able to enjoy a result without arrogance. Accepting failure without excuses. Appreciating the organisers, the rivals, the crew and the people who look after the event. It means bringing a good atmosphere with you and helping to make the regatta an experience for everyone." },
    z_no_p4: { sk: "Gentleman Sailing tak prirodzene prepája šport s kultúrou správania. Je to regata, kde sa súťaží, ale aj stretáva. Kde sa merajú sily, ale aj budujú vzťahy. Kde vietor v plachtách prináša adrenalín a spoločné večery prinášajú priateľstvá.", en: "Gentleman Sailing thus naturally connects sport with a culture of conduct. It is a regatta where people compete, but also meet. Where strength is measured, but relationships are built. Where wind in the sails brings adrenaline and shared evenings bring friendships." },
    z_ms_eb: { sk: "More spája", en: "The sea connects" },
    z_ms_t: { sk: "More ako priestor, ktorý spája", en: "The sea as a space that connects" },
    z_ms_p1: { sk: "More má zvláštnu schopnosť zbližovať ľudí. Na palube sa nedá zostať úplne bokom. Každý je súčasťou posádky, každý reaguje na rovnaký vietor, každého ovplyvní rovnaká vlna a každý smeruje k rovnakému cieľu.", en: "The sea has a special ability to bring people together. On board, nobody can stay completely on the sidelines. Everyone is part of the crew, everyone responds to the same wind, everyone is affected by the same wave and everyone is heading for the same goal." },
    z_ms_p2: { sk: "Práve preto je Gentleman Sailing viac než športové podujatie. Je to skúsenosť, ktorá prirodzene vytvára vzťahy. Na mori sa rozhovory vedú inak ako v kancelárii, v konferenčnej miestnosti alebo pri formálnom stole. Ľudia sa spoznávajú cez spoločný zážitok, cez rozhodnutia, cez humor, cez napätie aj cez okamihy ticha, keď loď ide pod plachtami a všetko ostatné na chvíľu stíchne.", en: "That is why Gentleman Sailing is more than a sporting event. It is an experience that naturally creates relationships. At sea, conversations flow differently than in an office, a conference room or at a formal table. People get to know each other through a shared experience, through decisions, through humour, through tension and through moments of silence when the boat is under sail and everything else goes quiet for a while." },
    z_ms_p3: { sk: "More odstraňuje zbytočné bariéry. Na palube nie je dôležité, kto má akú pracovnú pozíciu, titul alebo funkciu. Dôležité je, kto práve drží kormidlo, kto pomáha s lanom, kto sleduje vietor, kto podporí ostatných a kto vie v správnej chvíli zachovať pokoj.", en: "The sea removes needless barriers. On board it does not matter who holds which job, title or position. What matters is who is at the helm, who is helping with a rope, who is watching the wind, who supports the others and who can stay calm at the right moment." },
    z_ms_p4: { sk: "Aj preto je Gentleman Sailing silným zážitkom pre firmy, klientov, obchodných partnerov aj interné tímy. More vytvára prostredie, v ktorom sa prirodzene ukáže spolupráca, dôvera, rešpekt a schopnosť byť súčasťou jedného celku.", en: "That is also why Gentleman Sailing is such a powerful experience for companies, clients, business partners and internal teams. The sea creates an environment where cooperation, trust, respect and the ability to be part of a whole show themselves naturally." },
    z_po_eb: { sk: "Posádka", en: "The crew" },
    z_po_t: { sk: "Posádka ako symbol tímu", en: "The crew as a symbol of the team" },
    z_po_p1: { sk: "Na plachetnici nefunguje individualizmus bez ohľadu na ostatných. Každý člen posádky má svoju úlohu a každý pohyb má vplyv na celok. Ak jeden človek nereaguje, ovplyvní to ostatných. Ak posádka komunikuje jasne, loď ide lepšie. Ak si ľudia dôverujú, manévre sú plynulejšie. Ak sa tím podporuje, zvládne aj náročnejšie chvíle.", en: "On a sailing boat, individualism that ignores others does not work. Every crew member has a role and every movement affects the whole. If one person fails to react, it affects the others. If the crew communicates clearly, the boat sails better. If people trust each other, manoeuvres are smoother. If the team supports each other, it can handle the harder moments too." },
    z_po_p2: { sk: "Gentleman Sailing preto prirodzene ukazuje, čo znamená byť tímom. Nie v teórii, nie na workshope, nie cez prezentáciu. Ale priamo v praxi.", en: "Gentleman Sailing therefore naturally shows what it means to be a team. Not in theory, not at a workshop, not through a presentation. But directly in practice." },
    z_po_p3: { sk: "Posádka musí spolupracovať. Musí sa počúvať. Musí rešpektovať kapitána. Musí reagovať na meniace sa podmienky. Musí prijímať rozhodnutia. Musí zvládnuť tlak. Musí si pomáhať. A keď sa podarí dobrý manéver, dobrý štart alebo dobrý výsledok, radosť patrí všetkým.", en: "A crew must cooperate. It must listen. It must respect the skipper. It must respond to changing conditions. It must make decisions. It must handle pressure. It must help each other. And when a good manoeuvre, a good start or a good result comes off, the joy belongs to everyone." },
    z_po_p4: { sk: "To je sila regaty. Ukazuje, že tím nie je skupina ľudí na jednom mieste. Tím je skupina ľudí, ktorí dokážu ťahať jedným smerom.", en: "That is the power of a regatta. It shows that a team is not a group of people in one place. A team is a group of people who can pull in one direction." },
    z_tr_eb: { sk: "Tradícia", en: "Tradition" },
    z_tr_t: { sk: "Regata, ktorá má tradíciu", en: "A regatta with tradition" },
    z_tr_p1: { sk: "Gentleman Sailing má za sebou dlhoročnú tradíciu a mnoho posádok, lodí, firiem, moreplavcov, prístavov, trás, zážitkov a priateľstiev. Práve tradícia dáva regate váhu a charakter. Každý ročník prináša nové príbehy, no zároveň nadväzuje na atmosféru, ktorá sa budovala roky.", en: "Gentleman Sailing has a long tradition behind it and many crews, boats, companies, sailors, harbours, routes, experiences and friendships. It is tradition that gives the regatta its weight and character. Every edition brings new stories while building on an atmosphere created over many years." },
    z_tr_p2: { sk: "Táto kontinuita je dôležitá. Gentleman Sailing nie je jednorazové podujatie bez duše. Je to regata, ktorá má svoju históriu, svojich priaznivcov, svoje rituály a svoj osobitý spôsob, ako spájať ľudí na vode aj mimo nej.", en: "This continuity matters. Gentleman Sailing is not a one-off event without a soul. It is a regatta with its own history, its own followers, its own rituals and its own distinctive way of bringing people together on and off the water." },
    z_tr_p3: { sk: "Tradícia však neznamená uzavretosť. Naopak. Každý nový ročník prináša možnosť pridať sa. Vytvoriť vlastnú posádku, prihlásiť firmu, pozvať klientov, prísť s kolegami alebo sa jednoducho stať súčasťou komunity ľudí, ktorí rozumejú tomu, že plavba pod plachtami je viac než len presun z jedného miesta na druhé.", en: "Tradition, however, does not mean being closed. Quite the opposite. Every new edition brings the chance to join. To create your own crew, enter your company, invite clients, come with colleagues or simply become part of a community of people who understand that sailing is more than getting from one place to another." },
    z_pk_eb: { sk: "Pre koho", en: "Who it is for" },
    z_pk_t: { sk: "Pre koho je Gentleman Sailing určený?", en: "Who is Gentleman Sailing for?" },
    z_pk_p1: { sk: "Gentleman Sailing je určený pre všetkých, ktorí chcú zažiť regatu s atmosférou, úrovňou a priateľským duchom. Je vhodný pre skúsených jachtárov, ktorí si chcú užiť súťaž, aj pre účastníkov, ktorí prichádzajú za zážitkom, spoločnosťou a atmosférou mora.", en: "Gentleman Sailing is for everyone who wants to experience a regatta with atmosphere, standard and a friendly spirit. It suits experienced sailors who want to enjoy the competition as well as participants who come for the experience, the company and the atmosphere of the sea." },
    z_pk_p2: { sk: "Je vhodný pre mužov aj ženy. Pre firmy aj jednotlivcov. Pre obchodných partnerov aj interné tímy. Pre ľudí, ktorí milujú jachting, aj pre tých, ktorí sa s ním ešte len zoznamujú.", en: "It suits men and women. Companies and individuals. Business partners and internal teams. People who love yachting and those who are only just discovering it." },
    z_pk_p3: { sk: "Dôležité nie je, či ste už niekedy stáli pri kormidle. Dôležité je, či ste pripravení byť súčasťou posádky. Či viete rešpektovať pravidlá, spolupracovať, priložiť ruku k dielu a užiť si plavbu v duchu fair play.", en: "What matters is not whether you have ever stood at the helm. What matters is whether you are ready to be part of a crew. Whether you can respect the rules, cooperate, lend a hand and enjoy sailing in the spirit of fair play." },
    z_pk_p4: { sk: "Gentleman Sailing oslovuje ľudí, ktorí nehľadajú len program, ale zážitok. Nie iba súťaž, ale atmosféru. Nie iba cestu po mori, ale príbeh, ktorý budú rozprávať ešte dlho po návrate.", en: "Gentleman Sailing appeals to people who are not looking just for a programme, but for an experience. Not only a competition, but an atmosphere. Not only a voyage across the sea, but a story they will still be telling long after they return." },
    z_wg_eb: { sk: "Prečo gentleman", en: "Why gentleman" },
    z_wg_t: { sk: "Prečo „gentleman“?", en: "Why “gentleman”?" },
    z_wg_p1: { sk: "Slovo gentleman v názve Gentleman Sailing vyjadruje hodnoty, ktoré sú pre túto regatu podstatné. Nejde o formálny titul ani o uzavretý klub. Ide o spôsob správania.", en: "The word gentleman in the name Gentleman Sailing expresses the values that are essential to this regatta. It is not a formal title or a closed club. It is a way of behaving." },
    z_wg_p2: { sk: "Gentleman je človek, ktorý vie súťažiť bez arogancie. Vie vyhrať bez povýšenosti. Vie prehrať bez zatrpknutosti. Vie rešpektovať pravidlá, oceniť súpera a podržať vlastnú posádku. Vie, že sila nie je v hlučnosti, ale v charaktere. Vie, že férovosť nie je slabosť, ale základ skutočnej úrovne.", en: "A gentleman is someone who can compete without arrogance. Win without conceit. Lose without bitterness. Respect the rules, appreciate a rival and stand by their own crew. Someone who knows that strength lies not in loudness but in character, and that fairness is not weakness but the foundation of true class." },
    z_wg_p3: { sk: "V prostredí regaty sa tieto hodnoty prejavujú veľmi prirodzene. V tom, ako sa posádka správa pri štarte. Ako reaguje v náročnej situácii. Ako komunikuje s ostatnými loďami. Ako prijíma výsledky. Ako sa správa v prístave. Ako pristupuje k organizátorom, kapitánom, súperom aj hosťom.", en: "In a regatta these values show themselves very naturally. In how a crew behaves at the start. How it reacts in a difficult situation. How it communicates with other boats. How it accepts results. How it behaves in the harbour. How it treats the organisers, skippers, rivals and guests." },
    z_wg_p4: { sk: "Gentleman Sailing tak nie je len názov. Je to filozofia podujatia.", en: "Gentleman Sailing is thus not just a name. It is the philosophy of the event." },
    z_ru_eb: { sk: "Pravidlá & bezpečnosť", en: "Rules & safety" },
    z_ru_t: { sk: "Pravidlá, rešpekt a bezpečnosť", en: "Rules, respect and safety" },
    z_ru_p1: { sk: "Každá regata potrebuje pravidlá. Bez nich by súťaž nebola férová, bezpečná ani zmysluplná. V jachtingu majú pravidlá osobitý význam, pretože lode sa pohybujú v priestore, ktorý sa neustále mení. Vietor, vlny, rýchlosť, smer plavby a rozhodnutia posádok vytvárajú situácie, v ktorých je rešpektovanie pravidiel kľúčové.", en: "Every regatta needs rules. Without them the competition would be neither fair, nor safe, nor meaningful. In yachting, rules carry special weight because boats move in a space that is constantly changing. Wind, waves, speed, course and crew decisions create situations where respecting the rules is crucial." },
    z_ru_p2: { sk: "Na Gentleman Sailing má bezpečnosť a zodpovednosť svoje pevné miesto. Rešpekt ku kapitánovi, pokynom posádky, pravidlám regaty a podmienkam na mori nie je formalita. Je to základ toho, aby si všetci mohli podujatie užiť naplno.", en: "At Gentleman Sailing, safety and responsibility have a firm place. Respect for the skipper, the crew's instructions, the regatta rules and the conditions at sea is not a formality. It is the basis for everyone being able to enjoy the event to the full." },
    z_ru_p3: { sk: "Gentlemanská plavba znamená vedieť, že more je krásne, ale vyžaduje pokoru. Znamená nepodceňovať počasie, nepreceňovať vlastné schopnosti a rešpektovať rozhodnutia, ktoré chránia posádku aj loď.", en: "Gentleman sailing means knowing that the sea is beautiful but demands humility. It means not underestimating the weather, not overestimating your own abilities and respecting the decisions that protect the crew and the boat." },
    z_ru_p4: { sk: "Práve zodpovednosť robí z regaty bezpečný a hodnotný zážitok. Adrenalín má svoje miesto, ale nikdy nie na úkor rozumu, rešpektu a bezpečnosti.", en: "It is responsibility that makes the regatta a safe and worthwhile experience. Adrenaline has its place, but never at the expense of reason, respect and safety." },
    z_at_eb: { sk: "Atmosféra", en: "Atmosphere" },
    z_at_t: { sk: "Atmosféra, ktorá sa nedá naplánovať v zasadacej miestnosti", en: "An atmosphere you cannot plan in a meeting room" },
    z_at_p1: { sk: "Sú veci, ktoré sa nedajú vytvoriť umelo. Atmosféra pri rannom vyplávaní. Napätie pred štartom. Vietor, ktorý napne plachty. Radosť po vydarenom manévri. Ticho počas plavby. Smiech v prístave. Spoločná večera po dni na vode. Pocit, že ste boli súčasťou niečoho výnimočného.", en: "Some things cannot be created artificially. The atmosphere of setting sail in the morning. The tension before the start. The wind filling the sails. The joy after a well-executed manoeuvre. The silence while under way. The laughter in the harbour. A shared dinner after a day on the water. The feeling of having been part of something exceptional." },
    z_at_p2: { sk: "Gentleman Sailing vytvára práve takéto momenty. Nie je to iba program v harmonograme. Je to séria zážitkov, ktoré vznikajú prirodzene. Vďaka moru, ľuďom, súťaži, prostrediu a spoločnej energii.", en: "Gentleman Sailing creates exactly these moments. It is not just an item on a schedule. It is a series of experiences that arise naturally. Thanks to the sea, the people, the competition, the setting and the shared energy." },
    z_at_p3: { sk: "Pre firmy je to príležitosť, ako priniesť klientom alebo zamestnancom zážitok, ktorý má emóciu. Pre jednotlivcov je to možnosť stať sa súčasťou posádky, spoznať nových ľudí a zažiť jachting v jeho najkrajšej podobe.", en: "For companies it is an opportunity to give clients or employees an experience with real emotion. For individuals it is a chance to become part of a crew, meet new people and experience yachting at its finest." },
    z_at_p4: { sk: "Gentleman Sailing nie je udalosť, ktorú iba absolvujete. Je to udalosť, ktorú prežijete.", en: "Gentleman Sailing is not an event you merely attend. It is an event you live." },
    z_fr_eb: { sk: "Firemný rozmer", en: "The corporate dimension" },
    z_fr_t: { sk: "Firemný rozmer Gentleman Sailing", en: "The corporate dimension of Gentleman Sailing" },
    z_fr_p1: { sk: "Gentleman Sailing má prirodzene silný firemný rozmer. Mnohé firmy hľadajú spôsob, ako sa odlíšiť, ako ponúknuť klientom výnimočný zážitok alebo ako posilniť vlastný tím. Regata na mori na to vytvára ideálne prostredie.", en: "Gentleman Sailing naturally has a strong corporate dimension. Many companies look for a way to stand out, to offer clients an exceptional experience or to strengthen their own team. A regatta at sea creates the ideal environment for that." },
    z_fr_p2: { sk: "Na rozdiel od klasického firemného eventu prináša Gentleman Sailing skutočnú spoločnú skúsenosť. Klienti, partneri alebo zamestnanci nie sú iba divákmi programu. Sú jeho súčasťou. Nastupujú na palubu, stávajú sa posádkou, prežívajú deň na vode, súťažia, spolupracujú a zdieľajú zážitky.", en: "Unlike a classic corporate event, Gentleman Sailing offers a genuinely shared experience. Clients, partners or employees are not mere spectators of a programme. They are part of it. They step on board, become a crew, live a day on the water, compete, cooperate and share experiences." },
    z_fr_p3: { sk: "Takéto momenty vytvárajú vzťahy prirodzenejšie ako formálne stretnutia. Na mori sa rozhovory otvárajú ľahšie. Spoločný zážitok odbúrava odstup. Atmosféra regaty dáva priestoru networking, ale bez strojenosti. Vzniká prostredie, v ktorom sa ľudia spoznávajú cez zážitok, nie iba cez vizitky.", en: "Such moments build relationships more naturally than formal meetings. At sea, conversations open up more easily. A shared experience breaks down distance. The atmosphere of the regatta makes room for networking without stiffness. An environment arises where people get to know each other through the experience, not just through business cards." },
    z_fr_p4: { sk: "Pre firmy je Gentleman Sailing reprezentatívnym, no zároveň ľudským formátom podujatia. Spája noblesu jachtingu, energiu súťaže a silu spoločného zážitku.", en: "For companies, Gentleman Sailing is a representative yet human format. It combines the nobility of yachting, the energy of competition and the power of a shared experience." },
    z_tb_t: { sk: "Teambuilding, ktorý preverí aj spojí", en: "Teambuilding that tests and unites" },
    z_tb_p1: { sk: "Gentleman Sailing je mimoriadne vhodný aj ako teambuilding. Nie preto, že by ponúkal oddych pri mori, hoci aj ten k nemu patrí. Je vhodný najmä preto, že tímová spolupráca je na plachetnici skutočná a nevyhnutná.", en: "Gentleman Sailing is also exceptionally well suited to teambuilding. Not because it offers seaside relaxation, although that is part of it too. Above all because teamwork on a sailing boat is real and essential." },
    z_tb_p2: { sk: "Na lodi nie je tímová práca iba heslo. Je to každodenná realita. Posádka musí zvládnuť komunikáciu, rozdelenie úloh, rýchle rozhodnutia, koordináciu aj dôveru. Každý člen tímu vidí, že jeho prístup ovplyvňuje ostatných. Každý má šancu prispieť k spoločnému výsledku.", en: "On a boat, teamwork is not just a slogan. It is everyday reality. The crew must manage communication, division of roles, quick decisions, coordination and trust. Every team member sees that their attitude affects the others. Everyone has the chance to contribute to the common result." },
    z_tb_p3: { sk: "Takýto teambuilding má silný efekt, pretože nevzniká v umelo vytvorenej hre, ale v reálnom prostredí. More, vietor a loď vytvoria situácie, ktoré prirodzene ukážu, ako tím funguje. Kto dokáže viesť. Kto vie podporiť. Kto zostáva pokojný. Kto pomáha. Kto počúva. Kto povzbudí.", en: "Such teambuilding has a powerful effect because it happens not in an artificial game but in a real environment. The sea, the wind and the boat create situations that naturally reveal how the team works. Who can lead. Who can support. Who stays calm. Who helps. Who listens. Who encourages." },
    z_tb_p4: { sk: "A práve vďaka tomu si tím z Gentleman Sailing neodnáša iba pekné fotografie, ale aj skúsenosť, ktorá môže zlepšiť spoluprácu po návrate do pracovného života.", en: "And that is why a team takes home from Gentleman Sailing not just nice photographs, but an experience that can improve how they work together back in professional life." },
    z_ea_eb: { sk: "Pre každého účastníka", en: "For every participant" },
    z_ea_t: { sk: "Zážitok pre klientov, partnerov aj zamestnancov", en: "An experience for clients, partners and employees" },
    z_ea_p1: { sk: "Gentleman Sailing dokáže byť rôznymi vecami pre rôznych účastníkov. Pre klientov môže byť nezabudnuteľným eventom. Pre obchodných partnerov výnimočným pozvaním do neformálneho, no reprezentatívneho prostredia. Pre zamestnancov odmenou, motiváciou a príležitosťou zažiť kolegov inak. Pre vedenie firmy možnosťou budovať kultúru, vzťahy a dôveru.", en: "Gentleman Sailing can be different things for different participants. For clients, an unforgettable event. For business partners, an exceptional invitation into an informal yet representative setting. For employees, a reward, motivation and a chance to see colleagues differently. For company leadership, a way to build culture, relationships and trust." },
    z_ea_p2: { sk: "Práve univerzálnosť robí z regaty silný formát. Nie je to pasívny program, ktorý účastníci iba sledujú. Je to aktívny zážitok, do ktorého vstupujú. Každý si z neho odnáša niečo vlastné — adrenalín, pokoj, nové kontakty, priateľstvá, hrdosť na tím, radosť z mora alebo jednoducho pocit, že zažil niečo výnimočné.", en: "It is this versatility that makes the regatta such a strong format. It is not a passive programme participants merely watch. It is an active experience they step into. Everyone takes away something of their own — adrenaline, calm, new contacts, friendships, pride in the team, the joy of the sea, or simply the feeling of having experienced something exceptional." },
    z_du_p1: { sk: "Duch Gentleman Sailing sa nedá zhrnúť iba do výsledkovej listiny. Je v rannom pohybe v maríne. V príprave lodí. V očakávaní pred štartom. V pohľade na plachty ostatných posádok. V rozhodnutiach kapitánov. V práci posádky. V napätí počas pretekov. V radosti v cieli. V potlesku pri vyhodnotení. V rozhovoroch po regate. V zážitkoch, ktoré sa opakujú pri každom ďalšom stretnutí.", en: "The spirit of Gentleman Sailing cannot be summed up in a results sheet. It is in the morning bustle of the marina. In preparing the boats. In the anticipation before the start. In the sight of the other crews' sails. In the skippers' decisions. In the crew's work. In the tension during the races. In the joy at the finish. In the applause at the prize-giving. In the conversations after the regatta. In the experiences retold at every next meeting." },
    z_du_p2: { sk: "Je to duch súťaže bez nepriateľstva. Ambície bez arogancie. Dobrodružstva bez chaosu. Noblesy bez odstupu. Priateľstva bez hrania sa na niečo, čím nie sme.", en: "It is a spirit of competition without hostility. Ambition without arrogance. Adventure without chaos. Nobility without aloofness. Friendship without pretending to be something we are not." },
    z_du_p3: { sk: "Gentleman Sailing je regata pre ľudí, ktorí chcú zažiť more so štýlom, súťaž s rešpektom a spoločnosť s úrovňou.", en: "Gentleman Sailing is a regatta for people who want to experience the sea with style, competition with respect and company with class." },
    z_ta_eb: { sk: "Čo si odnesiete", en: "What you take away" },
    z_ta_t: { sk: "Čo si z Gentleman Sailing odnesiete?", en: "What will you take away from Gentleman Sailing?" },
    z_ta_p1: { sk: "Z Gentleman Sailing si neodnesiete iba výsledok. Odnesiete si skúsenosť, ktorú je ťažké nahradiť iným typom podujatia.", en: "You will take away more than a result from Gentleman Sailing. You will take away an experience that is hard to replace with any other kind of event." },
    z_ta_p2: { sk: "Odnesiete si pocit z plavby pod napnutými plachtami. Spomienku na spoločný štart. Radosť z dobre zvládnutého manévru. Úsmev po dni na vode. Nové kontakty. Silnejšie vzťahy. Príbehy, ku ktorým sa budete vracať. A možno aj chuť vrátiť sa na regatu opäť.", en: "You will take away the feeling of sailing under full sails. The memory of a shared start. The joy of a well-handled manoeuvre. A smile after a day on the water. New contacts. Stronger relationships. Stories you will keep coming back to. And perhaps the desire to return to the regatta again." },
    z_ta_p3: { sk: "Gentleman Sailing je o momentoch, ktoré vznikajú medzi ľuďmi. More je ich kulisou, vietor ich poháňa a regata im dáva smer.", en: "Gentleman Sailing is about the moments that arise between people. The sea is their backdrop, the wind drives them and the regatta gives them direction." },
    z_one_eb: { sk: "Gentleman Sailing v jednej vete", en: "Gentleman Sailing in one sentence" },
    z_pull: { sk: "Gentleman Sailing regata je súťažná, no priateľská plavba na mori, ktorá spája mužov aj ženy, firmy aj jednotlivcov, športový výkon aj noblesu, fair play aj dobrodružstvo a mení posádky na tímy.", en: "The Gentleman Sailing regatta is a competitive yet friendly voyage at sea that brings together men and women, companies and individuals, sporting performance and nobility, fair play and adventure — and turns crews into teams." },
    z_wj_eb: { sk: "Prečo sa pridať", en: "Why join" },
    z_wj_t: { sk: "Prečo sa pridať?", en: "Why join?" },
    z_wj_l1: { sk: "Pretože existujú zážitky, ktoré sa nedajú opísať z brehu.", en: "Because some experiences cannot be described from the shore." },
    z_wj_l2: { sk: "Pretože more spája ľudí inak ako akékoľvek iné prostredie.", en: "Because the sea connects people like no other environment." },
    z_wj_l3: { sk: "Pretože regata ukáže tím v pohybe, nie iba v slovách.", en: "Because a regatta shows a team in motion, not just in words." },
    z_wj_l4: { sk: "Pretože fair play, férovosť a noblesa majú v športe aj v biznise stále svoje miesto.", en: "Because fair play, fairness and nobility still have their place in sport and in business." },
    z_wj_l5: { sk: "Pretože Gentleman Sailing nie je len o tom, kto príde do cieľa prvý. Je o tom, kto sa na tejto ceste stane súčasťou príbehu.", en: "Because Gentleman Sailing is not only about who finishes first. It is about who becomes part of the story along the way." },
    z_cta_t: { sk: "Plavte sa s nami", en: "Sail with us" },
    z_cta_p1: { sk: "Vstúpte do sveta Gentleman Sailing a zažite regatu, v ktorej sa súťaží naplno, no s rešpektom. Regatu, v ktorej má každý člen posádky svoje miesto. Regatu, kde sa more, vietor, tím a noblesa spájajú do jedného nezabudnuteľného zážitku.", en: "Step into the world of Gentleman Sailing and experience a regatta raced flat out, yet with respect. A regatta where every crew member has their place. A regatta where the sea, the wind, the team and nobility merge into one unforgettable experience." },
    z_cta_p2: { sk: "Či prichádzate ako firma, posádka, jednotlivec, klient, partner alebo člen tímu, Gentleman Sailing vám ukáže, že skutočná plavba sa nezačína až na mori. Začína sa rozhodnutím vyplávať.", en: "Whether you come as a company, a crew, an individual, a client, a partner or a team member, Gentleman Sailing will show you that the real voyage does not begin at sea. It begins with the decision to set sail." },
    z_du_t: { sk: "Duch regaty", en: "The spirit of the regatta" },
    z_tagline: { sk: "Gentleman Sailing — regata, kde <em>fair play</em> drží kurz a vietor nesie zážitky.", en: "Gentleman Sailing — a regatta where <em>fair play</em> holds the course and the wind carries the experiences." },
    foot_tagline: { sk: 'Regata s noblesou a 20-ročnou tradíciou. Organizuje NautiTech, s.r.o.', en: 'A regatta of nobility with a 20-year tradition. Organised by NautiTech, s.r.o.' },
    foot_email_label: { sk: 'E-mail', en: 'E-mail' },
    foot_phone_label: { sk: 'Telefón', en: 'Phone' },
    foot_social_label: { sk: 'Sledujte nás', en: 'Follow us' },
    back: { sk: '← Späť na hlavnú stránku', en: '← Back to homepage' }
  };

  var lang = 'sk';
  try { if (localStorage.getItem('gs-lang') === 'en') lang = 'en'; } catch (e) {}

  function applyLang() {
    document.documentElement.lang = lang;
    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      var k = el.getAttribute('data-i18n');
      if (DICT[k]) el.textContent = DICT[k][lang];
    });
    document.querySelectorAll('[data-i18n-html]').forEach(function (el) {
      var kk = el.getAttribute('data-i18n-html');
      if (DICT[kk]) el.innerHTML = DICT[kk][lang];
    });
    var toggle = document.getElementById('langToggle');
    if (toggle) toggle.textContent = lang === 'sk' ? 'SK / en' : 'sk / EN';
  }

  var langToggle = document.getElementById('langToggle');
  if (langToggle) {
    langToggle.addEventListener('click', function () {
      lang = lang === 'sk' ? 'en' : 'sk';
      try { localStorage.setItem('gs-lang', lang); } catch (e) {}
      applyLang();
    });
  }

  var nav = document.getElementById('nav');
  function onScroll() {
    if (!nav) return;
    if (window.scrollY > 40) nav.classList.add('is-scrolled');
    else nav.classList.remove('is-scrolled');
  }
  window.addEventListener('scroll', onScroll, { passive: true });
  onScroll();

  var burger = document.getElementById('burger');
  var navLinks = document.getElementById('navLinks');
  if (burger && nav) {
    burger.addEventListener('click', function () {
      var open = nav.classList.toggle('is-open');
      burger.setAttribute('aria-expanded', open ? 'true' : 'false');
    });
  }
  if (navLinks) {
    navLinks.querySelectorAll('a').forEach(function (a) {
      a.addEventListener('click', function () {
        nav.classList.remove('is-open');
        if (burger) burger.setAttribute('aria-expanded', 'false');
      });
    });
  }

  applyLang();
})();
